<?php 
/**
 * Magento
 * @namespace   Magebuzz
 * @extension   Product Slider
 * @author   		Thomas
 * @version     0.1.1
 * @copyright   Copyright (c) 2015 Magebuzz Store. (http://www.magebuzz.com/)
 */

/******* Product Slider - head.phtml ******/
$helper = Mage::helper('productslider');
$sliderType = $helper->getSliderType(); 
$isIncludeJs = $helper->includeJs();
?>
<?php if ($helper->isActive()):?>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/magebuzz/productslider.css');?>" media="all" />
	<?php if ($isIncludeJs): ?>
		<script src="<?php echo $this->getSkinUrl('js/magebuzz/productslider/jquery-1.11.3.min.js'); ?>" type="text/javascript"></script>
		<script src="<?php echo $this->getSkinUrl('js/magebuzz/productslider/jquery.noconflict.js'); ?>" type="text/javascript"></script>
	<?php endif; ?>
	<?php if($sliderType == 'simple-slider'):?>
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/magebuzz/productslider/jquery.bxslider.min.js') ?>"></script>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/magebuzz/productslider/jquery.bxslider.min.css');?>" media="all" />
		<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/magebuzz/productslider/simple-slider.css');?>" media="all" />
		<script type="text/javascript">
			  jQuery(document).ready(function(){
					jQuery('#list-items').bxSlider();
			  });
		</script>
	<?php endif; ?>
	<?php if($sliderType == 'slider-scrollbar'):?>
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/magebuzz/productslider/jquery-ui.min.js') ?>"></script>
		<script type="text/javascript">
			jQuery(function() {				
				//vars
				var conveyor = jQuery(".content-conveyor", jQuery("#sliderContent")),
				item = jQuery(".item", jQuery("#sliderContent"));
				
				//set length of conveyor
				conveyor.css("width", item.length * parseInt(item.css("width")));
						
				//config
				var sliderOpts = {
				  max: (item.length * parseInt(item.css("width"))) - parseInt(jQuery(".viewer",jQuery("#sliderContent")).css("width")),
						slide: function(e, ui) { 
						conveyor.css("left", "-" + ui.value + "px");
				  }
				};

				//create slider
				jQuery("#slider").slider(sliderOpts);
			});
		</script>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/magebuzz/productslider/jquery-ui.min.css');?>" />
		<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/magebuzz/productslider/slidebar.css');?>" />
	<?php endif; ?>
	<?php if($sliderType == 'slider-lightbox'):?>
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/magebuzz/productslider/jquery.bxslider.min.js') ?>"></script>
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/magebuzz/productslider/lightbox/jquery.fancybox.pack.js') ?>"></script>
		<script type="text/javascript">
			var SKIN_URL = '<?php echo $this->getSkinUrl() ?>';
			jQuery(document).ready(function(){
				jQuery('#list-items').bxSlider({
					minSlides: 6,
					maxSlides: 6,
					slideWidth: 180,
					slideMargin: 10
				});
				jQuery('.lightbox').fancybox();
			});
		</script>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/magebuzz/productslider/jquery.bxslider.min.css');?>" media="all" />
		<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/magebuzz/productslider/jquery.fancybox.css') ?>" media="screen" />
	<?php endif; ?>
<?php endif; ?>